### ISSUE TITLE
ReShade4.91 ReShade5.22

### ISSUE THREAD

**Issue by garnetlol** [Rosiedog02/mb#1]
![ReShade_Setup_4 9 1](https://user-images.githubusercontent.com/102502473/229416054-82486b43-367c-44fe-971c-fb05567ec6c0.png)
![ReShade_Setup_5 2 2_Addon](https://user-images.githubusercontent.com/102502473/229416063-e0859c8b-0cd4-4f4d-b40b-f9f0d1bcaa22.png)

**Comment by Rosiedog02** [comment]
switched from ViewProjectionMatrix  to ViewPositionFromDepth

**Comment by garnetlol** [comment]
![ReShade5 2 2](https://user-images.githubusercontent.com/102502473/229416771-afb8b712-5df5-4665-958f-89e4c4363144.png)

**Comment by garnetlol** [comment]
> 从 ViewProjectionMatrix 切换到 ViewPositionFromDepth
thank you!
